### ISSUE TITLE
Remove hard-coded prints and use static errors

### ISSUE THREAD

**Issue by 0xjac** [sorenisanerd/go-trustedproxies#1]
This lib looks interesting but upon testing it out, I noticed a few things that could be improved:

1. Remove the hard-coded prints, specifically on lines: [70](https://github.com/sorenisanerd/go-trustedproxies/blob/c3bc2891fac6ac3e488ae4a43fa9cbfe8f100325/main.go#L70) and [74](https://github.com/sorenisanerd/go-trustedproxies/blob/c3bc2891fac6ac3e488ae4a43fa9cbfe8f100325/main.go#L74)
2. Do not define dynamic errors as on line [48](https://github.com/sorenisanerd/go-trustedproxies/blob/c3bc2891fac6ac3e488ae4a43fa9cbfe8f100325/main.go#L48), instead use a wrapped static error. Suggestion:
   ```go
   var ErrInvalidIPSpecification = errors.New("invalid IP specification") // place at the top of the file
   // ....
   return nil, fmt.Errorf("%w: %s", ErrInvalidIPSpecification, s)
   ```

**Comment by sorenisanerd** [comment]
Great suggestions! Would you mind whipping up a PR so you get credited appropriately?

**Comment by 0xjac** [comment]
@sorenisanerd there you go :slightly_smiling_face:

**Comment by sorenisanerd** [comment]
Thank you!
